#cmake -DCMAKE_TOOLCHAIN_FILE=a320.cmake -DCMAKE_BUILD_TYPE=Release
#make
#mv solarus solarus.dge

#LD_LIBRARY_PATH="./" ./solarus.dge

SET (A320 True)

SET (CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_VERSION 1)
SET (CMAKE_SYSTEM_PROCESSOR jz4740)

SET (DEVROOT /opt/opendingux-toolchain)
#SET (SYSROOT "${DEVROOT}/usr/mipsel-gcw0-linux-uclibc/sysroot")
SET (_CMAKE_TOOLCHAIN_PREFIX mipsel-unknown-linux-uclibc-)
SET (_CMAKE_TOOLCHAIN_LOCATION /usr/bin)

SET (CMAKE_FIND_ROOT_PATH "${DEVROOT}" "${SOLARUS_ENGINE_SOURCE_DIR}/libraries/a320")
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)