#cmake -DCMAKE_TOOLCHAIN_FILE=gcw0.cmake -DCMAKE_BUILD_TYPE=Release

SET (GCW0 True)

SET (CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_VERSION 1)
SET (CMAKE_SYSTEM_PROCESSOR jz4770)

SET (DEVROOT /opt/gcw0-toolchain)
SET (SYSROOT "${DEVROOT}/usr/mipsel-gcw0-linux-uclibc/sysroot")
SET (_CMAKE_TOOLCHAIN_PREFIX mipsel-gcw0-linux-uclibc-)
SET (_CMAKE_TOOLCHAIN_LOCATION /usr/bin)

SET (CMAKE_FIND_ROOT_PATH "${DEVROOT}" "${SYSROOT}" "${SOLARUS_ENGINE_SOURCE_DIR}/libraries/gcw0")
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)